"""Generate the synthetic year-long profiles in this directory.

Everything written here is synthetic, produced by the shape models below with
a fixed random seed. Nothing is measured data. Run from the repo root:

    python data/profiles/make_profiles.py

The load profile is a small summer-peaking utility, peak near 150 MW, with
seasonal, weekly and diurnal structure plus noise. The PV capacity factor is
a clear sky solar geometry model for a mid latitude site with autocorrelated
cloud attenuation on top. The wind capacity factor draws hourly speeds from a
Weibull distribution with autocorrelation, then passes them through the
toolkit power curve.
"""

from __future__ import annotations

import os
import sys

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "src"))
OUT = os.path.dirname(os.path.abspath(__file__))

from psa import renewables  # noqa: E402

HOURS = 8760
LATITUDE_DEG = 40.0


def write_csv(name, header_comment, columns):
    path = os.path.join(OUT, name)
    names = list(columns)
    with open(path, "w") as f:
        for line in header_comment.strip().splitlines():
            f.write(f"# {line.strip()}\n")
        f.write(",".join(names) + "\n")
        for row in zip(*columns.values()):
            f.write(",".join(f"{v:.4f}" if isinstance(v, float) else str(v) for v in row) + "\n")
    print("wrote", path)


def make_load(rng):
    h = np.arange(HOURS)
    day = h // 24
    hod = h % 24
    dow = day % 7
    # summer peaking season, maximum near day 200
    seasonal = 1.0 + 0.20 * np.cos(2 * np.pi * (day - 200) / 365.0)
    # double humped diurnal shape, morning rise and a stronger evening peak
    diurnal = (0.62
               + 0.16 * np.exp(-0.5 * ((hod - 9.0) / 2.5) ** 2)
               + 0.38 * np.exp(-0.5 * ((hod - 18.5) / 3.0) ** 2))
    weekly = np.where(dow >= 5, 0.90, 1.0)
    noise = 1.0 + 0.03 * rng.standard_normal(HOURS)
    load = 118.0 * seasonal * diurnal * weekly * noise
    return np.clip(load, 25.0, None)


def make_pv_cf(rng):
    h = np.arange(HOURS)
    day = h // 24
    hod = h % 24 + 0.5
    lat = np.deg2rad(LATITUDE_DEG)
    decl = np.deg2rad(23.45) * np.sin(2 * np.pi * (284 + day + 1) / 365.0)
    hour_angle = np.deg2rad(15.0 * (hod - 12.0))
    sin_elev = (np.sin(lat) * np.sin(decl)
                + np.cos(lat) * np.cos(decl) * np.cos(hour_angle))
    clear = np.clip(sin_elev, 0.0, None) ** 1.15  # crude air mass shaping
    # autocorrelated daily cloudiness, persistent over a few days
    z = np.zeros(365)
    for d in range(1, 365):
        z[d] = 0.7 * z[d - 1] + 0.3 * rng.standard_normal()
    cloud_day = np.clip(0.75 + 0.35 * z, 0.15, 1.0)
    hourly_flicker = np.clip(1.0 + 0.10 * rng.standard_normal(HOURS), 0.5, 1.0)
    cf = clear * cloud_day[day] * hourly_flicker
    return np.clip(cf, 0.0, 1.0)


def make_wind_cf(rng):
    # hourly speeds: AR(1) Gaussian mapped through the Weibull quantile
    # function, shape k = 2.1, scale c = 8.0 m/s
    k, c = 2.1, 8.0
    rho = 0.96
    z = np.zeros(HOURS)
    z[0] = rng.standard_normal()
    eps = rng.standard_normal(HOURS)
    for t in range(1, HOURS):
        z[t] = rho * z[t - 1] + np.sqrt(1 - rho**2) * eps[t]
    from scipy.stats import norm
    u = np.clip(norm.cdf(z), 1e-9, 1 - 1e-9)
    v = c * (-np.log(1.0 - u)) ** (1.0 / k)
    cf = renewables.wind_power(v, 1.0)
    return v, cf


def main():
    rng = np.random.default_rng(20260815)
    h = np.arange(HOURS)
    load = make_load(rng)
    write_csv("load_8760.csv", """
        Synthetic hourly load for a small utility, one non-leap year, MW.
        Generated by make_profiles.py with seed 20260815. Not measured data.
        Shape: summer peaking seasonal factor, double humped diurnal curve,
        weekend reduction, 3 percent Gaussian noise.
        """, {"hour": h, "load_mw": load.round(4)})
    pv = make_pv_cf(rng)
    write_csv("pv_cf_8760.csv", """
        Synthetic hourly PV capacity factor, one year, dimensionless 0 to 1.
        Generated by make_profiles.py with seed 20260815. Not measured data.
        Shape: clear sky solar elevation for latitude 40 N with autocorrelated
        daily cloud attenuation and hourly flicker.
        """, {"hour": h, "cf": pv.round(4)})
    v, wind = make_wind_cf(rng)
    write_csv("wind_cf_8760.csv", """
        Synthetic hourly wind capacity factor, one year, dimensionless 0 to 1.
        Generated by make_profiles.py with seed 20260815. Not measured data.
        Speeds drawn from a Weibull distribution, shape 2.1 and scale 8.0 m/s,
        with hour to hour autocorrelation, passed through the toolkit power
        curve with cut-in 3, rated 12 and cut-out 25 m/s.
        """, {"hour": h, "wind_speed_ms": v.round(4), "cf": wind.round(4)})
    print(f"load: peak {load.max():.1f} MW, min {load.min():.1f} MW, energy {load.sum()/1000:.1f} GWh")
    print(f"pv: annual capacity factor {pv.mean():.3f}")
    print(f"wind: annual capacity factor {wind.mean():.3f}, mean speed {v.mean():.2f} m/s")


if __name__ == "__main__":
    main()
